#[derive(Clone, Debug)]
pub enum ObjectType {
    Amf0Number(f64),
    Amf0Bool(bool),
    Amf0String(String),
    Amf0Object,
    Amf0Null,
    Amf0Undefined,
    Amf0EcmaArray,
    Amf0StrictArray,
    Amf0Date,
    Amf0LongString,
    Amf0XML,
    Amf0TypedObject,
    Amf0Switch,

    Amf3Undefined,
    Amf3Null,
    Amf3False,
    Amf3True,
    Amf3Integer(i32),
    Amf3Double(f64),
    Amf3String(String),
    Amf3XMLDocument,
    Amf3Date,
    Amf3Array(Vec<usize>),
    Amf3Object,
    Amf3XML,
    Amf3ByteArray,
    Amf3VectorInt,
    Amf3VectorUInt,
    Amf3VectorDouble,
    Amf3VectorObject,
    Amf3Dictionary,
}
